spring.application.name=MessageMicroService

spring.datasource.url=jdbc:mysql://localhost:3306/messagemicroservice?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.cloud.config.enabled=false


eureka.client.enabled=false
#Server configuration
server.port=8089
server.servlet.context-path=/messagemicro